[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && cd server && npm install && npm run build"

[deploy]
startCommand = "node server/dist/index.js"
restartPolicyType = "ON_FAILURE"

[nixpacks]
python_version = "3.10"

[nixpacks.aptPkgs]
packages = ["python3", "python3-pip", "python3-dev", "python3-venv", "libgl1-mesa-glx", "libglib2.0-0", "libsm6", "libxext6", "libxrender-dev", "libgomp1"]

[nixpacks.install]
cmd = """
python3 -m pip install --upgrade pip && \
pip3 install --no-cache-dir ultralytics opencv-python-headless scikit-image numpy pillow
"""

[nixpacks.env]
PYTHONPATH = "/app:/app/server"
PYTHONUNBUFFERED = "1"
PATH = "/usr/local/bin:/usr/bin:/bin:$PATH"