[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build && cd server && npm install && npm run build"

[deploy]
startCommand = "node server/dist/index.js"
restartPolicyType = "ON_FAILURE"